### PR TITLE
Conf be able to read/write anon reviewer groups

### PR DESCRIPTION
**Pull request by mohituniyal**
Add conference group as reader and writer for each new Anon-Reviewer group.

### CODE REVIEW

**Comment by melisabok** [comment]
We should do the same the builder is doing to assign reviewers to avoid inconsistencies.

Here is an example:

Screen Shot 2019-09-09 at 8 45 35 AM

**Comment by mohituniyal** [comment]
> We should do the same the builder is doing to assign reviewers to avoid inconsistencies.
> 
> Here is an example:
> 
> Screen Shot 2019-09-09 at 8 49 46 AM

**Comment by melisabok** [comment]
It seems the builder is setting up the AC as writers of Anon groups:

https://github.com/iesl/openreview-py/blob/master/openreview/conference/builder.py#L568

so, it should work, right?

**Comment by mohituniyal** [comment]
I made some changes to the set_assignment function in the builder. @melisabok please take a look, I think the groups (created by the builder and by the Ac/Pc consoles) are consistent now.

**Pull request merged**
