### PR TITLE
Fix bug where content in second tab would be pushed down by content in first tab

### PR DESCRIPTION
**Pull request by zbialecki**

### CODE REVIEW

**Comment by melisabok** [comment]
@pmandler could you check if this fixes it and then merge it?

**Comment by pmandler** [comment]
The problem doesn't show up in the regular Author Console, it only showed up in the copy that I modified for the Reproducibility Challenge.  I can test that it doesn't mess things up, but I can't really test if it fixes anything.

**Comment by melisabok** [comment]
what is the difference between one console and the other?

**Comment by zbialecki** [comment]
The difference was in the order of tabs. When the "Your Submissions" tab is first, this problem becomes visible. I wanted to fix it here so that if other conferences modify this base file the problem doesn't show up.

**Comment by pmandler** [comment]
Zach - cool, I didn't know that was the issue and I do thing Your Submissions should be the first tab because it's likely to be the most useful.
Melisa - Reproducibility shows both the Claim and the Report.

**Comment by melisabok** [comment]
Thank you both, I'm trying to do a quick test in my localhost and then I will merge it.

**Comment by melisabok** [comment]
The issue is fixed and I moved the submissions tab to the first position.

**Pull request merged**
