### PR TITLE
move template filling functions into tools.py and remove invitation-s…

### PR DESCRIPTION
**Pull request by mspector**
…pecific functionality.

Doesn't change anything about the way the function works.

### CODE REVIEW

**Comment by mspector** [comment]
tests are failing because the superuser password on dev has changed

**Comment by mohituniyal** [comment]
I think we should add some comments to these functions while we are placing them in tools.py because these functions will be visible in the ReadTheDocs documentation.

**Comment by mspector** [comment]
@mohituniyal what do we do about "private" functions? (I say "private" because python doesn't have any concept of truly private functions like Java, but the convention is to name functions with a leading underscore (e.g. `_fill_str`) when the function is not intended to be used by an outside caller)

**Comment by mohituniyal** [comment]
> @mohituniyal what do we do about "private" functions? (I say "private" because python doesn't have any concept of truly private functions like Java, but the convention is to name functions with a leading underscore (e.g. `_fill_str`) when the function is not intended to be used by an outside caller)

By default Sphinx does not generate documentation for "private" functions. So, we can choose not to annotate them. I would still request a 1 liner for each function just for future reference.

**Pull request merged**
