### PR TITLE
Feature/edges bid interface

### PR DESCRIPTION
**Pull request by zbialecki**
Update bid webfield template to use edges.

### CODE REVIEW

**Comment by melisabok** [comment]
Why do you have all these changes here? You should have a single commit that is the merge of master....

**Comment by zbialecki** [comment]
I don't know why! I think it must be because I branched off of feature/edges. Have any suggestions on how to fix it?

**Comment by melisabok** [comment]
feature/edges is up to date with master: https://github.com/iesl/openreview-py/compare/feature/edges?expand=1

I tried to update this branch with feature/edges but it didn't change anything

**Comment by melisabok** [comment]
Doing a comparison between these 2 branches doesn't show all the commits:  https://github.com/iesl/openreview-py/compare/feature/edges...feature/edges-bid-interface

may be you need to close the PR and create it again?

**Comment by zbialecki** [comment]
Oh I didn't realize you were updating feature/edges. I did the same for my branch thinking that David wanted to keep that as-is.

**Comment by melisabok** [comment]
I updated feature/edges a few minutes ago. 

Why would David want to keep it as it is? It should be always up-to-date with master.

**Comment by zbialecki** [comment]
He told me that his openreview-matcher tests all used an old version of the builder and they would break if he updated feature/edges with the latest code from master. @marshall62 correct me if I'm wrong.

**Pull request closed without merging**
