### PR TITLE
export invitations folder

### PR DESCRIPTION
**Pull request by melisabok**
@pmandler 

Could you check if your localhost works?

you should do:

```
pip install .
```

without the -e option

### CODE REVIEW

**Comment by pmandler** [comment]
How do I test it before merging it? Pip install . on its own did not work.

**Comment by melisabok** [comment]
you need to checkout this branch, could you?

**Comment by pmandler** [comment]
Yeah I tried:
   git checkout fix/invitation-export 
from the openreview-py directory where setup.py resides and I got:
   error: pathspec 'fix/invitation-export' did not match any file(s) known to git.
Then tried:
  git checkout --track fix/invitation-export
and got:
  fatal: Cannot update paths and switch to branch at the same time

**Comment by melisabok** [comment]
git fetch first?

**Comment by melisabok** [comment]
New version uploaded: https://pypi.org/project/openreview-py/0.8.0/

**Pull request merged**
