### PR TITLE
Feature/construct client with token

### PR DESCRIPTION
**Pull request by marshall62**
Added token to the constructor of Client

### CODE REVIEW

**Comment by melisabok** [comment]
@marshall62 I see unit tests failing, I think it is related to the new parameter in the constructor, could you take a look?

you can run the test from your machine:

```
pytest
```

The run against the dev site. 

or you can try to create a client:

```
openreview.Client(token='dddwfsdfsa')
```

and see if it works

**Comment by melisabok** [comment]
Master is working: https://circleci.com/gh/iesl/openreview-py

**Comment by melisabok** [comment]
Take a look at the test that is failing:

```
>       self.client = openreview.Client(baseurl = self.baseurl, username = "OpenReview.net")

tests/test_client.py:11: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python2.7/site-packages/openreview/openreview.py:74: in __init__
    self.login_user(self.username, self.password)
/usr/local/lib/python2.7/site-packages/openreview/openreview.py:119: in login_user
    response = self.__handle_response(response)
/usr/local/lib/python2.7/site-packages/openreview/openreview.py:93: in __handle_response
    if 'errors' in response.json():
/usr/local/lib/python2.7/site-packages/requests/models.py:896: in json
    return complexjson.loads(self.text, **kwargs)
/usr/local/lib/python2.7/json/__init__.py:339: in loads
    return _default_decoder.decode(s)
/usr/local/lib/python2.7/json/decoder.py:364: in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
```

**Comment by mspector** [comment]
Ah I see. @marshall62 there's your next clue.

**Comment by marshall62** [comment]
Do we know that the password in the test environment has been set correctly?  If its wrong then the line:
self.client = openreview.Client(baseurl = self.baseurl, username = "OpenReview.net")

can fail

**Comment by melisabok** [comment]
The client reads the password from environment variable if exists: https://github.com/iesl/openreview-py/blob/master/openreview/openreview.py#L51

CircleCI has this password set as an environment variable, and the tests in master are passing. 

Something in your code is making the tests fail.

**Pull request merged**
