### PR TITLE
Fix/pc console reassignment

### PR DESCRIPTION
**Pull request by zbialecki**
Fix issue with table data not updating after reviewer-reassignment

### CODE REVIEW

**Comment by melisabok** [comment]
Something weird it is happening when assign or un-assign a reviewer, this part of the UI is rendered several times? it is like the UI is shaking.

Screen Shot 2019-10-07 at 8 19 51 PM

**Comment by zbialecki** [comment]
Fixes #451

**Comment by melisabok** [comment]
This is awesome!

Search works perfectly. Next iteration: search by Area chairs name in Area Chair Status and reviewer name in Reviewer Name Status.

I'm still seeing the dropdown twice when I add an assignment and switch pages:

Screen Shot 2019-10-09 at 5 26 45 PM

I'm not sure if it is related to this PR but could you take a look Zach. I'm feeling kind of lost how the UI works now.

**Comment by melisabok** [comment]
I think I fixed it but I'm not sure if it is the correct fix.

**Comment by zbialecki** [comment]
I see now why that was happening. Your fix looks good to me.

**Comment by zbialecki** [comment]
The way search is implemented it should be easy to add to the Area Chair and Reviewers tabs.

**Comment by melisabok** [comment]
Sounds good. I think this PR is ready to merge. @mohituniyal?

We can add the search in another PR.

**Pull request merged**
